<script setup>
import { h, onMounted, reactive, ref } from 'vue'
import { PlusOutlined } from '@ant-design/icons-vue'
import { useRouter } from 'vue-router'
import WorkspaceLayout from '../../components/layout/WorkspaceLayout.vue'
import { listMyBorrowRequests } from '../../services/borrow.service'
import { useAuthStore } from '../../stores/auth'
const router=useRouter(),authStore=useAuthStore();const loading=ref(true),errorMessage=ref(''),result=ref({items:[],page:1,pageSize:10,total:0});const filters=reactive({status:undefined,page:1,pageSize:10})
const statusOptions=['PENDING','PARTIALLY_APPROVED','APPROVED','REJECTED','COMPLETED','CANCELLED'].map(value=>({value,label:value.replaceAll('_',' ')}))
const colors={PENDING:'orange',PARTIALLY_APPROVED:'processing',APPROVED:'success',REJECTED:'error',COMPLETED:'blue',CANCELLED:'default'}
const formatDate=value=>new Intl.DateTimeFormat('en-GB').format(new Date(value))
async function load(){loading.value=true;errorMessage.value='';try{result.value=await listMyBorrowRequests(authStore.api,filters)}catch(e){errorMessage.value=e.message||'Requests could not be loaded.'}finally{loading.value=false}}
function changePage(page){filters.page=page;void load()}onMounted(load)
</script>
<template><WorkspaceLayout><template #context><strong>My Requests</strong></template><main class="request-list-page"><header class="page-title"><div><h1>My Borrow Requests</h1><p>Manage your asset borrowing requests.</p></div><a-button v-if="authStore.hasPermission('borrow_request.create')" type="primary" :icon="h(PlusOutlined)" @click="router.push({name:'borrow-request-create'})">Create Borrow Request</a-button></header><section class="panel"><div class="filters"><a-select v-model:value="filters.status" allow-clear placeholder="All statuses" :options="statusOptions" @change="filters.page=1;load()" /></div><a-alert v-if="errorMessage" type="error" show-icon :message="errorMessage"/><a-table v-else :loading="loading" :data-source="result.items" row-key="id" :pagination="false"><a-table-column title="Request ID" key="id"><template #default="{record}"><a-button type="link" @click="router.push({name:'borrow-request-detail',params:{id:record.id}})">REQ-{{String(record.id).padStart(4,'0')}}</a-button></template></a-table-column><a-table-column title="Creation Date" key="created"><template #default="{record}">{{formatDate(record.createdAt)}}</template></a-table-column><a-table-column title="Asset Count" data-index="detailCount"/><a-table-column title="Approved" data-index="approvedCount"/><a-table-column title="Rejected" data-index="rejectedCount"/><a-table-column title="Status" key="status"><template #default="{record}"><a-tag :color="colors[record.status]">{{record.status.replaceAll('_',' ')}}</a-tag></template></a-table-column><a-table-column title="Action" key="action"><template #default="{record}"><a-button type="link" @click="router.push({name:'borrow-request-detail',params:{id:record.id}})">View details</a-button></template></a-table-column></a-table><footer><span>Showing {{result.items.length}} of {{result.total}} requests</span><a-pagination :current="result.page" :page-size="result.pageSize" :total="result.total" :show-size-changer="false" @change="changePage"/></footer></section></main></WorkspaceLayout></template>
<style scoped>.screen-code{color:#8c8c8c}.request-list-page{padding:24px;max-width:1320px;margin:auto}.page-title{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:20px}.page-title h1{margin:0;font-size:26px}.page-title p{color:#8c8c8c;margin:4px 0}.panel{background:#fff;border:1px solid #f0f0f0;border-radius:8px;min-height:560px;padding:16px}.filters{display:flex;gap:12px;margin-bottom:14px}.filters :deep(.ant-select){width:220px}footer{display:flex;justify-content:space-between;align-items:center;padding:14px 8px;color:#8c8c8c}@media(max-width:600px){.request-list-page{padding:12px}.page-title{gap:12px;flex-direction:column}}
</style>
