<script setup>
import { h, onMounted, reactive, ref } from 'vue'
import { PlusOutlined } from '@ant-design/icons-vue'
import { useRouter } from 'vue-router'
import StatusTag from '../../components/common/StatusTag.vue'
import { BORROW_REQUEST_STATUSES, statusLabel } from '../../constants/status-meta'
import WorkspaceLayout from '../../components/layout/WorkspaceLayout.vue'
import { listMyBorrowRequests } from '../../services/borrow.service'
import { useAuthStore } from '../../stores/auth'
const router=useRouter(),authStore=useAuthStore();const loading=ref(true),errorMessage=ref(''),result=ref({items:[],page:1,pageSize:10,total:0});const filters=reactive({status:undefined,page:1,pageSize:10})
const statusOptions=BORROW_REQUEST_STATUSES.map(value=>({value,label:statusLabel(value)}))
const formatDate=value=>new Intl.DateTimeFormat('en-GB').format(new Date(value))
async function load(){loading.value=true;errorMessage.value='';try{result.value=await listMyBorrowRequests(authStore.api,filters)}catch(e){errorMessage.value=e.message||'Requests could not be loaded.'}finally{loading.value=false}}
function changePage(page){filters.page=page;void load()}onMounted(load)
</script>
<template><WorkspaceLayout><template #context><strong>My Requests</strong></template><main class="request-list-page bigin-page-container"><header class="page-title"><div><h1>My Borrow Requests</h1><p>Manage your asset borrowing requests.</p></div><a-button v-if="authStore.hasPermission('borrow_request.create')" class="bigin-touch-target" type="primary" :icon="h(PlusOutlined)" @click="router.push({name:'borrow-request-create'})">Create Borrow Request</a-button></header><section class="panel"><div class="filters"><a-select v-model:value="filters.status" allow-clear placeholder="All statuses" :options="statusOptions" @change="filters.page=1;load()" /></div><a-alert v-if="errorMessage" type="error" show-icon :message="errorMessage"/><div v-else class="bigin-table-scroll-wrapper"><a-table :loading="loading" :data-source="result.items" row-key="id" :pagination="false" :scroll="{ x: 'max-content' }"><a-table-column title="Request ID" key="id" :width="150"><template #default="{record}"><a-button class="bigin-touch-target" type="link" @click="router.push({name:'borrow-request-detail',params:{id:record.id}})">REQ-{{String(record.id).padStart(4,'0')}}</a-button></template></a-table-column><a-table-column title="Creation Date" key="created" :width="160"><template #default="{record}">{{formatDate(record.createdAt)}}</template></a-table-column><a-table-column title="Asset Count" data-index="detailCount" :width="120"/><a-table-column title="Approved" data-index="approvedCount" :width="110"/><a-table-column title="Rejected" data-index="rejectedCount" :width="110"/><a-table-column title="Status" key="status" :width="140"><template #default="{record}"><StatusTag :status="record.status" /></template></a-table-column><a-table-column title="Action" key="action" :width="150"><template #default="{record}"><a-button class="bigin-touch-target" type="link" @click="router.push({name:'borrow-request-detail',params:{id:record.id}})">View details</a-button></template></a-table-column></a-table></div><footer class="bigin-responsive-footer"><span>Showing {{result.items.length}} of {{result.total}} requests</span><a-pagination class="bigin-touch-target" :current="result.page" :page-size="result.pageSize" :total="result.total" :show-size-changer="false" @change="changePage"/></footer></section></main></WorkspaceLayout></template>
<style scoped>.screen-code{color:var(--bigin-text-tertiary)}.request-list-page{padding:24px;max-width:1320px;margin:auto}.page-title{display:flex;justify-content:space-between;align-items:flex-start;gap:16px;margin-bottom:20px}.page-title h1{margin:0;font-size:26px}.page-title p{color:var(--bigin-text-tertiary);margin:4px 0}.panel{background:var(--bigin-surface-panel);border:1px solid var(--bigin-border-secondary);border-radius:8px;min-height:560px;padding:16px}.filters{display:flex;flex-wrap:wrap;gap:12px;margin-bottom:14px}.filters :deep(.ant-select){max-width:100%;width:220px}footer{color:var(--bigin-text-tertiary);padding:14px 8px}@media(max-width:767px){.request-list-page{padding:16px}.page-title{flex-direction:column}.page-title :deep(.ant-btn){width:100%}}@media(max-width:575px){.request-list-page{padding:12px}.filters :deep(.ant-select){width:100%}}
</style>
